//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Royalty.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserName
    {
        public int ID { get; set; }
        public string Username1 { get; set; }
        public string Password { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Country { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Email { get; set; }
        public Nullable<int> Createby { get; set; }
        public Nullable<System.DateTime> Createday { get; set; }
        public Nullable<int> Updateby { get; set; }
        public Nullable<System.DateTime> Updateday { get; set; }
    }
}
